### ISSUE TITLE
Episode Audio Issues

### ISSUE THREAD

**Issue by xoWhspr** [one-pace/onepace.net#66]
I've recently began using One Pace to get through the series and I'm now on Punk Hazard. I've noticed the audio on the episodes are sometimes distorted and jank? I haven't completed the arc yet so I dunno if it gets better further down the line but at the point where I'm at (The Beginning of the arc) the audio is really distorted and seems low quality. Mostly during the OP and It's noticeable throughout the episode as well. Dunno if this qualifies as a bug but I thought I should at least report it.

**Comment by sewil** [comment]
Not a website bug, the audio is just really bad for some of the early streams. I recommend torrenting.
